export default function Head() {
    return (
      <>
        <title>Finance Tracker</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.svgrepo.com/show/482978/dollar-money.svg" />
      </>
    )
  }